image: docker

services:
    - docker:dind

stages:
    - deploy

deploy_app:
    stage: deploy
    script:
        - docker-compose build --no-cache
        - docker-compose up -d
    only:
        - dev
        - master
    when: manual

